services:
    frontend:
        build:
            context: ./client
        container_name: frontend
        ports:
            - "3000:80" # port 3000 will be accessible on host machine
        depends_on:
            - backend
        networks:
            - app-network

    backend:
        build: ./server
        container_name: backend
        env_file:
            - ./server/.env
        ports:
            - "5000:5000"  # Expose backend port for development
        depends_on:
            - mongodb
        networks:
            - app-network

    mongodb:
        image: mongo:7.0
        container_name: mongodb
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password123
            MONGO_INITDB_DATABASE: recipe-app
        volumes:
            - mongodb_data:/data/db
        networks:
            - app-network

volumes:
    mongodb_data:

networks:
    app-network:
        driver: bridge
