apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            imagePullSecrets:
                - name: docker-hub-secret
            containers:
                - name: backend
                  image: sopheaktraleng/recipe-app-backend:latest
                  ports:
                      - containerPort: 5000
                  envFrom:
                      - configMapRef:
                            name: backend-config
                      - secretRef:
                            name: backend-secret
