apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "5000"
  DATABASE: "mongodb://admin:<PASSWORD>@mongodb-service:27017/recipe-app?authSource=admin"
  JWT_EXPIRES_IN: "3d"
  NODE_ENV: "development"
