apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            imagePullSecrets:
                - name: docker-hub-secret
            containers:
                - name: frontend
                  image: sopheaktraleng/recipe-app-frontend:latest
                  ports:
                      - containerPort: 80
                  volumeMounts:
                      - name: nginx-config
                        mountPath: /etc/nginx/conf.d/default.conf
                        subPath: default.conf
            volumes:
                - name: nginx-config
                  configMap:
                      name: frontend-nginx-config
