apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  mongodb.conf: |
    # MongoDB configuration
    storage:
      dbPath: /data/db
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
    net:
      port: 27017
      bindIp: 0.0.0.0
  init-script.js: |
    // MongoDB initialization script
    db = db.getSiblingDB('recipe-app');

    // Create collections if they don't exist
    if (!db.getCollectionNames().includes('recipes')) {
      db.createCollection('recipes');
    }

    if (!db.getCollectionNames().includes('users')) {
      db.createCollection('users');
    }

    print('Database initialization completed');
