apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  clusterIP: None   # Headless service for StatefulSet
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
