apiVersion: v1
kind: Secret
metadata:
    name: docker-hub-secret
    namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: |
        {
          "auths": {
            "https://index.docker.io/v1/": {
              "username": "sopheaktraleng",
              "password": "YOUR_DOCKER_HUB_TOKEN",
              "auth": "BASE64_ENCODED_USERNAME:PASSWORD"
            }
          }
        }
