apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
# NOTE: This is just a template - DO NOT commit real credentials!
# The Jenkins pipeline will create this secret automatically
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "sopheaktraleng",
          "password": "YOUR_DOCKER_HUB_TOKEN",
          "auth": "BASE64_ENCODED_USERNAME:PASSWORD"
        }
      }
    }
